# Generated by Django 5.0.6 on 2024-06-12 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='email',
        ),
    ]
