# Generated by Django 5.0.6 on 2024-06-12 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_task_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='name',
        ),
    ]
