# Generated by Django 5.0.6 on 2024-06-12 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_alter_loggedinuser_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
        migrations.DeleteModel(
            name='LoggedInUser',
        ),
        migrations.DeleteModel(
            name='task',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
